---
    - name: partition disks
      parted:
        device: "{{ item.value.pVol }}"
        number: 1
        state: present
        flags: [ "{{ item.value.appOption }}" ]
        label: gpt
        part_start: 2048s #disk alignment 
      with_dict: "{{ disks }}"

    - name: ensure volume groups
      lvg:
        vg: "{{ item.value.volGroup }}"
        state: present
        pvs: "{{ item.value.pVol + '1' }}"
      with_dict: "{{ disks }}"

    - name: ensure logcical volumes
      lvol:
        lv: lv_{{ item.value.mountPoint.split('/')[-1] }}
        state: present
        vg: "{{ item.value.volGroup }}"
        size: 100%VG
      with_dict: "{{ disks }}"

    - name: ensure filesystems
      filesystem:
        fstype: "{{ item.value.fstype }}"
        dev: /dev/mapper/{{ item.value.volGroup }}-lv_{{ item.value.mountPoint.split('/')[-1] }}
      with_dict: "{{ disks }}"

    - name: ensure filesystem mounts
      mount:
        path: "{{item.value.mountPoint }}"
        fstype: "{{ item.value.fstype }}"
        state: mounted
        src: /dev/mapper/{{ item.value.volGroup }}-{{ item.value.mountPoint.split('/')[-1] }}
      with_dict: "{{ disks }}"
...
